name: AWS Service CI/CD

on:
  push:
    branches: [ "main" ]  # Trigger deployment on push to main
  pull_request:
    branches: [ "main" ]  # Trigger CDK diff on PR

env:
  AWS_REGION: "eu-central-1"

permissions:
  contents: read
  pull-requests: write  # Needed to add PR comments

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # Install your Python dependencies here
          npm install -g aws-cdk

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run CDK Diff (only for pull requests)
        if: github.event_name == 'pull_request'
        id: cdk_diff
        run: |
          cdk diff || echo "No differences found." > cdk_diff_output.txt
        continue-on-error: true

      - name: Post CDK Diff to PR Comment
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DIFF_OUTPUT=$(cdk diff || echo "No differences found.")
          gh pr comment ${{ github.event.pull_request.number }} --body "$DIFF_OUTPUT"

      - name: Deploy to AWS (only for push to main or after PR merge)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cdk deploy --require-approval=never
