name: AWS Service CI/CD

on:
  push:
    branches: [ "main" ]  # Trigger deployment on push to main
  pull_request:
    branches: [ "main" ]  # Trigger CDK diff on PR

env:
  AWS_REGION: "eu-central-1"

permissions:
  contents: read
  pull-requests: write  # Needed to add PR comments

jobs:
  # Job for setting up environment and installing dependencies
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv/
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          npm install -g aws-cdk

      - name: Run CDK Diff
        if: github.event_name == 'pull_request'
        id: cdk_diff
        run: |
          cdk diff || echo "No differences found." > cdk_diff_output.txt
        continue-on-error: true

      - name: Post CDK Diff to PR Comment
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DIFF_OUTPUT=$(cdk diff || echo "No differences found.")
          gh pr comment ${{ github.event.pull_request.number }} --body "$DIFF_OUTPUT"

      - name: Deploy to AWS
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cdk deploy --require-approval=never
