name: AWS Service CI/CD

on:
  push:
    branches: [ "main" ]  # Trigger deployment on push to main
  pull_request:
    branches: [ "main" ]  # Trigger CDK diff on PR

env:
  AWS_REGION: "eu-central-1"

permissions:
  contents: read
  pull-requests: write  # Needed to add PR comments

jobs:
  # Job for setting up environment and installing dependencies
  setup_and_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv/
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          npm install -g aws-cdk

      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install Node.js dependencies
        run: npm install

  # Job for running CDK diff
  cdk_diff:
    runs-on: ubuntu-latest
    needs: setup_and_install
    if: github.event_name == 'pull_request'
    steps:
      - name: Run CDK Diff
        id: cdk_diff
        run: |
          cdk diff || echo "No differences found." > cdk_diff_output.txt
        continue-on-error: true

      - name: Post CDK Diff to PR Comment
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DIFF_OUTPUT=$(cdk diff || echo "No differences found.")
          gh pr comment ${{ github.event.pull_request.number }} --body "$DIFF_OUTPUT"

  # Job for deploying to AWS
  cdk_deploy:
    runs-on: ubuntu-latest
    needs: setup_and_install
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to AWS
        run: cdk deploy --require-approval=never
